routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('home', function (){
    echo 'Hello echo<br>';
    return 'Hello programmer.';
});

//Route::get('test',function (){TestController.index} -> name('test.index'));
Route::get('test', 'TestController@index') -> name('test.index');
Route::get('/home', 'HomeController@index') -> name('home');
Route::prefix('coffee')->name('coffee.')->namespace('coffee')->group(function (){
    Route::get('/home', 'NewHomeController@index') -> name('home');
    Route::get('/login', 'NewHomeController@login') -> name('login');
    Route::get('/user/details/{name}', 'NewHomeController@user_details') -> name('user.details');
});
Route::resource('product', 'ProductController');
//Route::get('/test', '');

Route::get('buyer/home', 'Buyer\HomeController@index');
Route::get('buyer/about','Buyer\HomeController@about');

Route::get('/buyer/register', 'Buyer\Auth\RegisterController@showRegistrationForm');
Route::post('/buyer/register', 'Buyer\Auth\RegisterController@register')->name('buyer.register');
Route::get('/seller/register', 'Seller\Auth\RegisterController@showRegistrationForm');
Route::post('/seller/register', 'Seller\Auth\RegisterController@register')->name('seller.register');





Route::get('order/mail', function (){
    return view('order');
} );

Route::post('order/mail', 'OrderController@send_email')-> name('order.mail');

Route::get('admin/login', 'Admin\Auth\LoginController@index');
Route::get('buyer/login', 'Buyer\Auth\LoginController@showLoginForm');
Route::post('buyer/login','Buyer\Auth\LoginController@Login')->name('buyer.login');
Route::get('seller/login', 'Seller\Auth\LoginController@index');


//buyer password reset
Route::post('buyer/password/email','Buyer\Auth\ForgotPasswordController@sendResetLinkEmail')->name('buyer.password.email');
Route::get('buyer/password/reset','Buyer\Auth\ForgotPasswordController@showLinkRequestForm')->name('buyer.password.request');
Route::post('buyer/password/reset','Buyer\Auth\ResetPasswordController@reset');
Route::get('buyer/password/reset/{token}','Buyer\Auth\ResetPasswordController@showResetForm')->name('buyer.password.reset');
//Route::


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Admin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Admin extends Model
{
    //

}

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    //
}

app/Buyer.php
<?php

namespace App;

use App\Notifications\BuyerResetPasswordNotification;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Buyer extends Authenticatable
{
    //
    use Notifiable;
    protected $fillable = [
        'first_name', 'second_name', 'email', 'phone_number', 'status', 'password'
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new BuyerResetPasswordNotification($token));
    }
}

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    //
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
}

app/Checkout.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Checkout extends Model
{
    //
}

app/Delivery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Delivery extends Model
{
    //
}

app/Image.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    //
}

app/Odour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Odour extends Model
{
//    public function send($build){
//
//    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    //
}

app/OrderProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OrderProduct extends Model
{
    //
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/ProductVariantOption.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductVariantOption extends Model
{
    //
}

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    //
}

app/Review.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    //
}

app/Seller.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Seller extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Variant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Variant extends Model
{
    //
}

app/VariantOption.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VariantOption extends Model
{
    //
}

app/Wishlist.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wishlist extends Model
{
    //
}

resources/views/admin/layout/auth_master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>@yield('title')</title>
</head>
<body>
<div class="container">
<h3>Register here</h3>
@yield('content')
<h3>This is buyer footer.</h3>
</div>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/login.blade.php
<html>
<head>
    <title>
        Login
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body><div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>        </div>
    </div>
</div></body>
</html>

resources/views/new_home.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">    <title>Laravel</title>    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">    {{--bootstrap--}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }        .full-height {
                     height: 100vh;
                 }        .flex-center {
                              align-items: center;
                              display: flex;
                              justify-content: center;
                          }        .position-ref {
                                       position: relative;
                                   }        .top-right {
                                                position: absolute;
                                                right: 10px;
                                                top: 18px;
                                            }        .content {
                                                         text-align: center;
                                                     }        .title {
                                                                  font-size: 84px;
                                                              }        .links > a {
                                                                           color: #636b6f;
                                                                           padding: 0 25px;
                                                                           font-size: 13px;
                                                                           font-weight: 600;
                                                                           letter-spacing: .1rem;
                                                                           text-decoration: none;
                                                                           text-transform: uppercase;
                                                                       }        .m-b-md {
                                                                                    margin-bottom: 30px;
                                                                                }
    </style>
</head>
<body>
<div class="flex-center position-ref full-height">
    @if (Route::has('login'))
        <div class="top-right links bg-dark">
            @auth
                <a href="{{ url('/home') }}">Home</a>
            @else
                {{--                <a href="{{ route('login') }}">Login</a>--}}{{--                @if (Route::has('register'))--}}
                {{--                    <a href="{{ route('register') }}">Register</a>--}}
                {{--                @endif--}}
            @endauth
        </div>
    @endif    <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <a href="{{route('coffee.user.details', ['name'=>$name])}}" class="btn btn-dark">View Details</a>
            </div>
        </div>
        <div class="title m-b-md">
            Laravel
        </div>        <div class="links">
            <a href="https://laravel.com/docs">Docs</a>
            <a href="https://laracasts.com">Laracasts</a>
            <a href="https://laravel-news.com">News</a>
            <a href="https://blog.laravel.com">Blog</a>
            <a href="https://nova.laravel.com">Nova</a>
            <a href="https://forge.laravel.com">Forge</a>
            <a href="https://github.com/laravel/laravel">GitHub</a>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/order.blade.php
@extends('buyer.layout.master')
@section('content')
    <div class="container">
    <button type="submit" class="btn-primary">Order{{route('order.mail')}}</button>
    </div>
    @endsection

resources/views/test.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{$page_title}}</title>
</head>
<body>
    <h1>Whatever {{$heading}}</h1>
    <p>Wharever</p>

</body>
</html>

resources/views/user_details.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">    <title>Used Details</title>    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">    {{--bootstrap--}}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Nunito', sans-serif;
            font-weight: 200;
            height: 100vh;
            margin: 0;
        }        .full-height {
                     height: 100vh;
                 }        .flex-center {
                              align-items: center;
                              display: flex;
                              justify-content: center;
                          }        .position-ref {
                                       position: relative;
                                   }        .top-right {
                                                position: absolute;
                                                right: 10px;
                                                top: 18px;
                                            }        .content {
                                                         text-align: center;
                                                     }        .title {
                                                                  font-size: 84px;
                                                              }        .links > a {
                                                                           color: #636b6f;
                                                                           padding: 0 25px;
                                                                           font-size: 13px;
                                                                           font-weight: 600;
                                                                           letter-spacing: .1rem;
                                                                           text-decoration: none;
                                                                           text-transform: uppercase;
                                                                       }        .m-b-md {
                                                                                    margin-bottom: 30px;
                                                                                }
    </style>
</head>
<body>
<div class="flex-center position-ref full-height">
    @if (Route::has('login'))
        <div class="top-right links bg-dark">
            @auth
                <a href="{{ url('/home') }}">Home</a>
            @else
                {{--                <a href="{{ route('login') }}">Login</a>--}}{{--                @if (Route::has('register'))--}}
                {{--                    <a href="{{ route('register') }}">Register</a>--}}
                {{--                @endif--}}
            @endauth
        </div>
    @endif    <div class="content">
        <h4>Details for {{$name}}</h4>
        <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
            industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into
            electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like
            Aldus PageMaker including versions of Lorem Ipsum.
        </p>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>